levelMap = ['                          ',
            '                          ',
            '                          ',
            '                          ',
            '   XX         XX          ',
            '            XX            ',
            '       X  XXXX    XX  XX  ',
            '       X  XXXX    XX  XXX ',
            'P   XXXX  XXXXXX  XX  XXXX',
            'XXXXXXXX  XXXXXX  XX  XXXX']