levelMap = ['                                                                      ',
            '                                                                      ',
            '                                                                      ',
            '                                                                      ',
            '   XX         XX                                                      ',
            '         P  XX    DC                                                  ',
            '       X  XXXX    XX  XX                                              ',
            '       X  XXXX    XX  XXX             C  M  O                         ',
            '    xxxX  XXXXXX  XX  XXXX                                            ',
            'xxxxXXXX  XXXXXX  XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']