levelMap = ['                          ',
            '                          ',
            '                          ',
            '                          ',
            '   XX         XX          ',
            '         P  XX            ',
            '       X  XXXX    XX  XX  ',
            '       X  XXXX    XX  XXX ',
            '    XXXX  XXXXXX  XX  XXXX',
            'XXXXXXXX  XXXXXX  XX  XXXX']